const pageKey = document.body.dataset.page;
const page = pages[pageKey] || pages.projects;
const nav = [["Games","games.html","games"],["Tools","tools.html","tools"],["2D Art","2dart.html","arts"],["Projects","projects.html","projects"],["Blogs","blogs.html","blogs"],["About","about.html","about"]];

function header(){ return `<header class="site-header"><a class="brand" href="index.html"><span class="brand-mark">TL</span><span>Tiancheng Li</span></a><nav class="navigation" aria-label="Main navigation">${nav.map(([label,url,key])=>`<a href="${url}" ${key===pageKey?'aria-current="page"':''}>${label}</a>`).join("")}</nav></header>`; }

function items(){ if (!page.items.length) return `<section class="blog-list page-frame" aria-label="Blog posts"><p class="empty-posts">No posts yet.</p></section>`; return `<section class="collection-list page-frame" id="work" data-section="Work">${page.items.map(([number,title,type,description,color],index)=>`<article class="collection-item"><a class="collection-art ${color}" href="${detailUrl(pageKey,title)}" aria-label="View ${title}"><span>${number}</span><strong>${title}</strong></a><div class="collection-details"><small>${type}</small><h2><a class="project-title-link" href="${detailUrl(pageKey,title)}">${title}</a></h2><p>${description}</p></div></article>`).join("")}</section>`; }

function gallery(){ return `<section class="gallery-section page-frame" id="gallery" data-section="Gallery"><div class="art-gallery">${artworks.map(([image,title,category,year,size],index)=>`<figure class="gallery-item gallery-item--${size}"><a class="gallery-image" href="${detailUrl(pageKey,title)}" aria-label="View ${title}"><img src="${image}" alt="${title}" loading="${index<2?'eager':'lazy'}"></a><figcaption><div><h2><a class="project-title-link" href="${detailUrl(pageKey,title)}">${title}</a></h2><p>${category}</p></div><span>${year}</span></figcaption></figure>`).join("")}</div></section>`; }

document.querySelector("#collection-page").innerHTML = `${header()}<main><section class="collection-hero page-frame" id="intro" data-section="Intro" style="--collection-color:${page.color}"><p>${page.number} / PORTFOLIO</p><h1>${page.title}<em>.</em></h1><div>${page.intro}</div></section>${pageKey==="arts"?gallery():items()}</main><footer class="site-footer"><span>&copy; 2026 Tiancheng Li</span><span>Art & Game Design Portfolio</span><a href="index.html">Return home &#8593;</a></footer>`;
